### ISSUE TITLE
OCP\Files\NotPermittedException

### ISSUE THREAD

**Issue by kevinkuan1969** [julien-nc/welcome#29]
After upgrade to Nextcloud 25.0.2, always to see the error messages related to Welcome widget. 
Here the error message from the log:

<html>
<body>

OCP\Files\NotPermittedException: /var/www/nextcloud/apps/welcome/lib/Service/FileService.php - line 177:OC\Files\Node\File->getContent()/var/www/nextcloud/apps/welcome/lib/Listener/CSPListener.php - line 57:OCA\Welcome\Service\FileService->getWidgetHttpImageUrls()/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php - line 87:OCA\Welcome\Listener\CSPListener->handle()/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:OC\EventDispatcher\ServiceEventListener->__invoke()/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:Symfony\Component\EventDispatcher\EventDispatcher->callListeners()/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 88:Symfony\Component\EventDispatcher\EventDispatcher->dispatch()/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 100:OC\EventDispatcher\EventDispatcher->dispatch()/var/www/nextcloud/lib/private/Security/CSP/ContentSecurityPolicyManager.php - line 60:OC\EventDispatcher\EventDispatcher->dispatchTyped()/var/www/nextcloud/lib/private/AppFramework/Middleware/Security/CSPMiddleware.php - line 71:OC\Security\CSP\ContentSecurityPolicyManager->getDefaultPolicy()/var/www/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php - line 143:OC\AppFramework\Middleware\Security\CSPMiddleware->afterController()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 171:OC\AppFramework\Middleware\MiddlewareDispatcher->afterController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1047:OC\Route\Router->match()/var/www/nextcloud/index.php - line 36:OC::handleRequest()
--

</body>
</html>

**Comment by julien-nc** [comment]
Hi, thanks for the bug report. I need more information to understand what happens to you and try to reproduce the bug.

I've never seen that on my side.

* NC version
* Welcome app version
* Did you configure the Welcome app?
* If so, does it work?
* Does this error show up when accessing the Dashboard page as the user who owns the Welcome markdown file or not?
* Anything else that can help :grin:

**Comment by kevinkuan1969** [comment]
NC version - 25.0.2
Welcome app version - 1.0.6
Did you configure the Welcome app? Yes and please find below

![image](https://user-images.githubusercontent.com/80019930/211246423-5495b1e0-8453-4b7b-aad7-65604309de73.png)

Managed to solve it by deleting the filecache using below SQL statement and disable/enable using OCC  command. 
It works perfectly and no more error message.
 
1. mysql> DELETE f FROM oc_filecache AS f INNER JOIN oc_mounts AS m ON m.storage_id = f.storage

  WHERE size < 0 AND parent > 1;
2. sudo -u www-data php occ app:remove welcome

**Comment by julien-nc** [comment]
Ok so everything works fine now, right?

Feel free to reopen if needed.
