### ISSUE TITLE
Error with new users since 1.0.6

### ISSUE THREAD

**Issue by leuedaniel** [julien-nc/welcome#30]
Since version 1.0.6, an error message appears for newly created cloud users when they try to log in to the cloud for the first time.

[index] Fehler: OCP\Files\NotPermittedException:  at <<closure>>

 0. /var/www/html/apps/welcome/lib/Service/FileService.php line 177
    OC\Files\Node\File->getContent()
 1. /var/www/html/apps/welcome/lib/Listener/CSPListener.php line 57
    OCA\Welcome\Service\FileService->getWidgetHttpImageUrls()
 2. /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php line 87
    OCA\Welcome\Listener\CSPListener->handle()
 3. /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 4. /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 5. /var/www/html/lib/private/EventDispatcher/EventDispatcher.php line 88
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
 6. /var/www/html/lib/private/EventDispatcher/EventDispatcher.php line 100
    OC\EventDispatcher\EventDispatcher->dispatch()
 7. /var/www/html/lib/private/Security/CSP/ContentSecurityPolicyManager.php line 60
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
 8. /var/www/html/lib/private/AppFramework/Middleware/Security/CSPMiddleware.php line 71
    OC\Security\CSP\ContentSecurityPolicyManager->getDefaultPolicy()
 9. /var/www/html/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php line 143
    OC\AppFramework\Middleware\Security\CSPMiddleware->afterController()
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 171
    OC\AppFramework\Middleware\MiddlewareDispatcher->afterController()
11. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
12. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
13. /var/www/html/lib/base.php line 1047
    OC\Route\Router->match()
14. /var/www/html/index.php line 36
    OC::handleRequest()

GET /apps/dashboard/

**Comment by leuedaniel** [comment]
I think its the same error like https://github.com/julien-nc/welcome/issues/29
NC-Version: 25.0.3
Welcome App Version: 1.0.6
![image](https://user-images.githubusercontent.com/44936305/217057900-4ac662b3-d4f9-41df-8906-fa38a4fc0498.png)
The error only appears when I create a new user in Nextcloud and the user tries to log in for the first time.

**Comment by julien-nc** [comment]
I can't reproduce on my side. Anyway I made an attempt to fix this. Could someone try v1.0.8 which is out?

**Comment by leuedaniel** [comment]
Now it works, thanks for the fix.
